[project]
name = "glarvis3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.84.0",
    "fastapi>=0.135.1",
    "pipecat-ai[cartesia,deepgram,groq,local,openai,silero,speechmatics,webrtc]>=0.0.104",
    "pygetwindow>=0.0.9",
    "python-dotenv>=1.2.2",
    "pywin32>=311",
    "uvicorn>=0.41.0",
]
